FROM alpine:3.10

RUN apk add curl && \
    curl --fail https://storage.googleapis.com/kubernetes-release/release/v1.16.0/bin/linux/amd64/kubectl > /bin/kubectl && \
    chmod 0755 /bin/kubectl

CMD while true;do sleep 3600; done
